services:
  - type: web
    name: chat-app
    runtime: node
    buildCommand: npm run build
    startCommand: npm --prefix Backend start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_TOKEN
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
